# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app.core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='publicacion',
            field=models.TextField(null=True),
        ),
    ]
